logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8c516c4557302aa5ec1748eb314531ce   # REST API 키
            client-secret: nzVsoYU5OHl4Q3SUGgd7XUNVuArm6K5k
            redirect-uri: http://localhost:8080/auth/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, 	account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
jwt:
  secretKey: secretkeysecretkeysecretkeysecretkeysecretkey
  access:
    expiration: 3600000
  refresh:
    expiration: 86400000